//Mail and Chat Channels
N(OP_MailLogin),
N(OP_Mail),
N(OP_ChannelMessage),
N(OP_ChannelAnnounceJoin),
N(OP_ChannelAnnounceLeave),
N(OP_MailSendHeaders),
N(OP_MailSendBody),
N(OP_MailDeliveryStatus),
N(OP_MailboxChange),
N(OP_MailNew),
