#simple root level makefile by Father Nitwit

all:
	$(MAKE) -C EMuShareMem
	$(MAKE) -C world
	$(MAKE) -C zone
	$(MAKE) -C eqlaunch


clean:
	$(MAKE) -C EMuShareMem clean
	$(MAKE) -C world clean
	$(MAKE) -C zone clean
	$(MAKE) -C eqlaunch clean

